name: nodejs-test

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74
          override: true
          components: clippy, rustfmt

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: pnpm
          cache-dependency-path: "nodejs/pnpm-lock.yaml"

      - name: Installing Dependencies
        working-directory: nodejs
        run: pnpm install

      - name: Building
        working-directory: nodejs
        run: pnpm build

      - name: Testing
        working-directory: nodejs
        run: pnpm test
